# Generated by Django 5.2.9 on 2026-01-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('db', 'Database'), ('media', 'Media')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField(help_text='Size in bytes')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
