# Generated by Django 5.2.9 on 2026-01-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_page_alter_product_description_alter_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Example: 123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Example: G-XXXXXXXXXX', max_length=50),
        ),
    ]
