# Generated by Django 5.2.9 on 2026-01-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='聯絡地址'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, verbose_name='Footer 關於我們'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='Copyright © 2026 PrintSmart.hk', max_length=200, verbose_name='Footer 版權宣告'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 文字 (標題)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_link',
            field=models.URLField(blank=True, verbose_name='Banner 連結'),
        ),
    ]
