# Generated by Django 5.2.9 on 2026-01-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_caption',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='按鈕文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 副標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 標題'),
        ),
    ]
