# Generated by Django 5.2.9 on 2026-01-28 03:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_sitesettings_hero_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='代碼')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('instructions', ckeditor.fields.RichTextField(blank=True, verbose_name='付款指示 (顯示於結帳頁)')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '付款方式',
                'verbose_name_plural': '付款方式',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='付款證明 (入數紙)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', '已建立'), ('paid', '已付款'), ('fulfilling', '備貨中'), ('shipped', '已出貨'), ('completed', '已完成'), ('canceled', '已取消'), ('returned', '退貨'), ('refunded', '已退費')], default='created', max_length=20, verbose_name='狀態'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.paymentmethod', verbose_name='付款方式'),
        ),
    ]
