# Generated by Django 5.2.9 on 2026-01-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_paymentmethod_order_payment_proof_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', '已建立'), ('paid', '已付款'), ('fulfilling', '備貨中'), ('partially_shipped', '部份交付'), ('shipped', '已出貨'), ('completed', '已完成'), ('canceled', '已取消'), ('returned', '退貨'), ('refunded', '已退費')], default='created', max_length=20, verbose_name='狀態'),
        ),
    ]
