# Generated by Django 5.2.9 on 2026-01-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount (定額)'), ('percent', 'Percentage (百分比)')], default='fixed', max_length=10, verbose_name='折扣類型'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage (e.g. 10 for 10%)', max_digits=10, verbose_name='折扣數值'),
        ),
    ]
