# Generated by Django 5.2.9 on 2026-01-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coupon_description_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_bg_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='選單背景顏色'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_items',
            field=models.TextField(blank=True, help_text='輸入選單項目，以逗號分隔 (例如: HP, Canon, Epson)。若留空則顯示預設項目。', verbose_name='選單項目'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='選單文字顏色'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_label_bg_color',
            field=models.CharField(default='#0d6efd', max_length=20, verbose_name='產品品牌標籤背景顏色'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_label_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='產品品牌標籤文字顏色'),
        ),
    ]
