# Generated by Django 5.2.9 on 2026-01-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_sitesettings_navbar_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_contact_text',
            field=models.CharField(default='聯絡我們', max_length=50, verbose_name='主選單-聯絡我們文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_home_text',
            field=models.CharField(default='主頁', max_length=50, verbose_name='主選單-主頁文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_store_text',
            field=models.CharField(default='商店', max_length=50, verbose_name='主選單-商店文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_tutorial_link',
            field=models.CharField(default='#', max_length=200, verbose_name='主選單-教學連結'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_tutorial_text',
            field=models.CharField(default='購物流程教學', max_length=50, verbose_name='主選單-教學文字'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_bg_color',
            field=models.CharField(default='#0d6efd', help_text='Hex color code (e.g. #0d6efd)', max_length=20, verbose_name='產品標籤背景顏色'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_text_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code (e.g. #ffffff)', max_length=20, verbose_name='產品標籤文字顏色'),
        ),
    ]
