# Generated by Django 5.2.9 on 2026-01-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_sitesettings_menu_contact_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='top_bar_bg_color',
            field=models.CharField(default='#F50057', help_text='Hex color code (e.g. #F50057)', max_length=20, verbose_name='頂部通知列背景顏色'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_bg_color',
            field=models.CharField(default='#D32F2F', help_text='Hex color code (e.g. #D32F2F)', max_length=20, verbose_name='導航列背景顏色'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_text_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code (e.g. #ffffff)', max_length=20, verbose_name='導航列文字顏色'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_bg_color',
            field=models.CharField(default='#000000', help_text='Hex color code (e.g. #0d6efd)', max_length=20, verbose_name='產品標籤背景顏色'),
        ),
    ]
