# Generated by Django 5.2.9 on 2026-01-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_sitesettings_top_bar_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_items',
            field=models.TextField(blank=True, default='HP, CANON, BROTHER, EPSON, SAMSUNG, XEROX, PANTUM, LEXMARK, KODAK, 其他商品', help_text='輸入選單項目，以逗號分隔 (例如: HP, Canon, Epson)。若留空則顯示預設項目。', verbose_name='選單項目'),
        ),
    ]
