# Generated by Django 5.2.9 on 2026-01-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_sitesettings_navbar_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '銷售報表 Dashboard',
                'verbose_name_plural': '銷售報表 Dashboard',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='created_by',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_proof',
            field=models.BooleanField(default=False, verbose_name='需要上傳證明'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣數值'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', '百分比'), ('fixed', '固定金額')], default='percent', max_length=20, verbose_name='折扣類型'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notes', to='store.order', verbose_name='訂單'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_items',
            field=models.TextField(default='HP, CANON, BROTHER, EPSON, SAMSUNG, XEROX, PANTUM, LEXMARK, KODAK, 其他商品', help_text='Comma separated list', verbose_name='導航列項目'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_bg_color',
            field=models.CharField(default='#D32F2F', max_length=20, verbose_name='商品標籤背景顏色'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='商品標籤文字顏色'),
        ),
    ]
