# Generated by Django 5.2.9 on 2026-01-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_salesdashboard_remove_ordernote_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='圖片')),
                ('image_url', models.URLField(blank=True, verbose_name='圖片連結')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='說明文字')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品圖片',
                'verbose_name_plural': '商品圖片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
