# Generated by Django 5.2.9 on 2026-01-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='圖片')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='標題')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副標題')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='按鈕文字')),
                ('link', models.URLField(blank=True, verbose_name='連結')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '首頁輪播圖',
                'verbose_name_plural': '首頁輪播圖',
                'ordering': ['sort_order'],
            },
        ),
    ]
