# Generated by Django 5.2.9 on 2026-01-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='寄件者 Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP 主機 (Host)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP 密碼 (Password)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP 端口 (Port)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='使用 TLS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP 帳號 (User)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='建議尺寸: 1920x450 像素 (寬x高)', upload_to='hero_slides/', verbose_name='圖片'),
        ),
    ]
