# Generated by Django 5.2.9 on 2026-01-29 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_sitesettings_smtp_from_email_sitesettings_smtp_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='is_customer_note',
            field=models.BooleanField(default=False, verbose_name='發送給客戶'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
