# Generated by Django 5.2.9 on 2026-02-02 03:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='分類名稱'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='分類名稱'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='按鈕文字'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button_text_zh_hant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='按鈕文字'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='副標題'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='副標題'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='標題'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='標題'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_zh_hant',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='標題'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_zh_hant',
            field=models.CharField(max_length=200, null=True, verbose_name='標題'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructions_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='付款指示 (顯示於結帳頁)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructions_zh_hant',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='付款指示 (顯示於結帳頁)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='名稱'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='名稱'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hant',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名稱'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_zh_hant',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名稱'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='規格'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_zh_hant',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='規格'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='說明文字'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='說明文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Footer 關於我們'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='Footer 關於我們'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_en',
            field=models.CharField(blank=True, default='Copyright © 2026 PrintSmart.hk', max_length=200, null=True, verbose_name='Footer 版權宣告'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_zh_hant',
            field=models.CharField(blank=True, default='Copyright © 2026 PrintSmart.hk', max_length=200, null=True, verbose_name='Footer 版權宣告'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='按鈕文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_text_zh_hant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='按鈕文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner 副標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner 副標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner 標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner 標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_contact_text_en',
            field=models.CharField(default='聯絡我們', max_length=50, null=True, verbose_name='主選單-聯絡我們文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_contact_text_zh_hant',
            field=models.CharField(default='聯絡我們', max_length=50, null=True, verbose_name='主選單-聯絡我們文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_home_text_en',
            field=models.CharField(default='主頁', max_length=50, null=True, verbose_name='主選單-主頁文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_home_text_zh_hant',
            field=models.CharField(default='主頁', max_length=50, null=True, verbose_name='主選單-主頁文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_store_text_en',
            field=models.CharField(default='商店', max_length=50, null=True, verbose_name='主選單-商店文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_store_text_zh_hant',
            field=models.CharField(default='商店', max_length=50, null=True, verbose_name='主選單-商店文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_tutorial_text_en',
            field=models.CharField(default='購物流程教學', max_length=50, null=True, verbose_name='主選單-教學文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_tutorial_text_zh_hant',
            field=models.CharField(default='購物流程教學', max_length=50, null=True, verbose_name='主選單-教學文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='My E-Shop', max_length=100, null=True, verbose_name='網站名稱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_zh_hant',
            field=models.CharField(default='My E-Shop', max_length=100, null=True, verbose_name='網站名稱'),
        ),
    ]
