# Generated by Django 5.2.9 on 2026-02-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_category_name_en_category_name_zh_hant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='聯絡地址'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='聯絡地址'),
        ),
    ]
