# Generated by Django 5.2.9 on 2026-02-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_sitesettings_contact_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='instructions_en',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='instructions_zh_hant',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name_zh_hant',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='caption_en',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='caption_zh_hant',
        ),
    ]
