# Generated by Django 5.2.9 on 2026-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_coupon_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='特色區塊圖片'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_subtitle',
            field=models.CharField(blank=True, default='加入我們對食物的精雕細琢之旅，感受我們的美食文化與獨特風格', max_length=500, verbose_name='特色區塊副標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_title',
            field=models.CharField(blank=True, default='我們有什麽', max_length=200, verbose_name='特色區塊標題'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='Copyright © 2026 GWZ', max_length=200, verbose_name='Footer 版權宣告'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_en',
            field=models.CharField(blank=True, default='Copyright © 2026 GWZ', max_length=200, null=True, verbose_name='Footer 版權宣告'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_zh_hant',
            field=models.CharField(blank=True, default='Copyright © 2026 GWZ', max_length=200, null=True, verbose_name='Footer 版權宣告'),
        ),
    ]
