# Generated by Django 5.2.9 on 2026-02-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_sitesettings_feature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_opening_hours',
            field=models.CharField(blank=True, default='週一至週日: 10:00AM - 10:00PM', max_length=255, verbose_name='營業時間'),
        ),
    ]
