# Generated by Django 5.2.9 on 2026-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_sitesettings_contact_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='創辦人照片'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_intro_text',
            field=models.TextField(blank=True, default='加入王子的美食之旅，享受生活中的美好事物！', verbose_name='創辦人區塊文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_intro_title',
            field=models.CharField(blank=True, default='平凡中見不凡', max_length=200, verbose_name='創辦人區塊標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_name',
            field=models.CharField(blank=True, default='王子', max_length=100, verbose_name='創辦人名稱'),
        ),
    ]
