# Generated by Django 5.2.9 on 2026-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_sitesettings_founder_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_opening_hours_en',
            field=models.CharField(blank=True, default='週一至週日: 10:00AM - 10:00PM', max_length=255, null=True, verbose_name='營業時間'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_opening_hours_zh_hant',
            field=models.CharField(blank=True, default='週一至週日: 10:00AM - 10:00PM', max_length=255, null=True, verbose_name='營業時間'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_subtitle_en',
            field=models.CharField(blank=True, default='加入我們對食物的精雕細琢之旅，感受我們的美食文化與獨特風格', max_length=500, null=True, verbose_name='特色區塊副標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_subtitle_zh_hant',
            field=models.CharField(blank=True, default='加入我們對食物的精雕細琢之旅，感受我們的美食文化與獨特風格', max_length=500, null=True, verbose_name='特色區塊副標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_title_en',
            field=models.CharField(blank=True, default='我們有什麽', max_length=200, null=True, verbose_name='特色區塊標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_title_zh_hant',
            field=models.CharField(blank=True, default='我們有什麽', max_length=200, null=True, verbose_name='特色區塊標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_intro_text_en',
            field=models.TextField(blank=True, default='加入王子的美食之旅，享受生活中的美好事物！', null=True, verbose_name='創辦人區塊文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_intro_text_zh_hant',
            field=models.TextField(blank=True, default='加入王子的美食之旅，享受生活中的美好事物！', null=True, verbose_name='創辦人區塊文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_intro_title_en',
            field=models.CharField(blank=True, default='平凡中見不凡', max_length=200, null=True, verbose_name='創辦人區塊標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_intro_title_zh_hant',
            field=models.CharField(blank=True, default='平凡中見不凡', max_length=200, null=True, verbose_name='創辦人區塊標題'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_name_en',
            field=models.CharField(blank=True, default='王子', max_length=100, null=True, verbose_name='創辦人名稱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_name_zh_hant',
            field=models.CharField(blank=True, default='王子', max_length=100, null=True, verbose_name='創辦人名稱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_items_en',
            field=models.TextField(default='HP, CANON, BROTHER, EPSON, SAMSUNG, XEROX, PANTUM, LEXMARK, KODAK, 其他商品', help_text='Comma separated list', null=True, verbose_name='導航列項目'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_items_zh_hant',
            field=models.TextField(default='HP, CANON, BROTHER, EPSON, SAMSUNG, XEROX, PANTUM, LEXMARK, KODAK, 其他商品', help_text='Comma separated list', null=True, verbose_name='導航列項目'),
        ),
    ]
