# Generated by Django 5.2.9 on 2026-02-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_sitesettings_contact_opening_hours_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_about_text',
            field=models.CharField(default='關於我們', max_length=50, verbose_name='主選單-關於我們文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_about_text_en',
            field=models.CharField(default='關於我們', max_length=50, null=True, verbose_name='主選單-關於我們文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_about_text_zh_hant',
            field=models.CharField(default='關於我們', max_length=50, null=True, verbose_name='主選單-關於我們文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_blog_text',
            field=models.CharField(default='博客', max_length=50, verbose_name='主選單-博客文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_blog_text_en',
            field=models.CharField(default='博客', max_length=50, null=True, verbose_name='主選單-博客文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_blog_text_zh_hant',
            field=models.CharField(default='博客', max_length=50, null=True, verbose_name='主選單-博客文字'),
        ),
    ]
