
import os
import polib

po_file_path = 'locale/zh_Hant/LC_MESSAGES/django.po'

translations = {
    "Traditional Chinese": "繁體中文",
    "English": "英文",
    "Welcome Call 66208132": "歡迎致電 66208132 訂購",
    "Logout": "登出",
    "Search for products": "搜尋產品",
    "Search products": "搜尋產品",
    "All Categories": "所有分類",
    "Menu": "選單",
    "Home": "主頁",
    "Store": "商店",
    "Blog": "博客",
    "Contact": "聯絡我們",
    "Contact Us": "聯絡我們",
    "Tutorial": "購物流程教學",
    "Categories": "分類",
    "Shopping cart": "購物車",
    "Shopping Cart": "購物車",
    "Your cart is empty.": "您的購物車是空的。",
    "Start Shopping": "開始購物",
    "Subtotal:": "小計:",
    "View Cart": "查看購物車",
    "Checkout": "結帳",
    "Login": "登入",
    "Register": "註冊",
    "My Account": "我的帳戶",
    "Account": "帳戶",
    "Username or email address": "使用者名稱或電子郵件地址",
    "Password": "密碼",
    "Remember me": "記住我",
    "Lost your password?": "忘記密碼？",
    "Add to cart": "加入購物車",
    "Pick your favorite": "挑選您喜愛的",
    "High quality": "高品質",
    "Quick Links": "快速連結",
    "About Us": "關於我們",
    "Latest Products": "最新產品",
    "Contact Info": "聯絡資訊",
    "Follow Us": "關注我們",
    "Language": "語言",
    "Username": "使用者名稱",
    "Email": "電子郵件",
    "Phone": "電話",
    "Address": "地址",
    "First Name": "名字",
    "Last Name": "姓氏",
    "User Name": "使用者名稱",
    "This email is already registered": "此電子郵件已被註冊",
    "Log In": "登入",
    "Username or Email": "使用者名稱或電子郵件",
    "Registering for this site allows you to access your order status and history. Just fill in the fields below, and we'll get a new account set up for you in no time. We will only ask you for information necessary to make the purchase process faster and easier.": "註冊此網站可讓您存取訂單狀態和歷史記錄。只需填寫以下欄位，我們將立即為您建立新帳戶。我們只會詢問您購買過程所需的信息。",
    "Specializing in sales of major brand printers and consumables, providing professional after-sales service and technical support.": "專營各大品牌打印機及耗材銷售，提供專業售後服務及技術支援。",
    "123 Some Street, Some District, Kowloon, Hong Kong": "香港九龍某區某街道123號",
    "Register Account": "註冊帳戶",
    "Register New Account": "註冊新帳戶",
    "Already have an account?": "已經有帳戶？",
    "Log In Now": "立即登入",
    "LOG IN": "登入",
    "Product": "產品",
    "Price": "價格",
    "Quantity": "數量",
    "Subtotal": "小計",
    "Total": "總計",
    "Remove": "移除",
    "Continue Shopping": "繼續購物",
    "Billing Details": "帳單資訊",
    "Company Name (Optional)": "公司名稱 (選填)",
    "Country / Region": "國家 / 地區",
    "Hong Kong": "香港",
    "Street Address": "街道地址",
    "House number and street name": "門牌號碼和街道名稱",
    "Apartment, suite, unit, etc. (optional)": "公寓、套房、單位等 (選填)",
    "Town / City": "城鎮 / 城市",
    "District": "地區",
    "Kowloon": "九龍",
    "Hong Kong Island": "香港島",
    "New Territories": "新界",
    "Email Address": "電子郵件地址",
    "Order Notes (Optional)": "訂單備註 (選填)",
    "Notes about your order, e.g. special notes for delivery.": "關於您的訂單的備註，例如運送特別說明。",
    "Your Order": "您的訂單",
    "Shipping": "運送",
    "Free Shipping": "免運費",
    "Coupon Code": "優惠券代碼",
    "Apply": "套用",
    "Discount": "折扣",
    "Place Order": "下訂單",
    "Shopping Guide": "購物指南",
    "Select Item / Color / Quantity": "選擇商品 / 顏色 / 數量",
    "Register as Member": "註冊成為會員",
    "Get Latest Offers": "獲取最新優惠",
    "Shipping Method": "運送方式",
    "Pickup / Express / Mail": "自取 / 快遞 / 郵寄",
    "Payment Method": "付款方式",
    "Bank Transfer / PayMe / FPS": "銀行轉帳 / PayMe / FPS",
    "Receive Goods": "收貨",
    "Wishlist": "我的最愛",
    "Remove from Wishlist": "從我的最愛移除",
    "View Details": "查看詳情",
    "Go Shopping": "去購物",
    "Featured Products": "精選產品",
    "Lifestyle & Culture": "生活與文化",
    "Beyond cooking, we invite you to see the world through George's eyes, sharing his experiences in travel, shopping, and different cultures.": "除了烹飪，我們邀請您透過 George 的眼睛看世界，分享他在旅行、購物和不同文化中的經歷。",
    "Address:": "地址:",
    "Opening Hours:": "營業時間:",
    "Enquiries:": "查詢:",
    "Email:": "電郵:",
    "Phone:": "電話:",
    "Mon - Sun: 10:00AM - 10:00PM": "週一至週日: 10:00AM - 10:00PM",
    "Prince has created a variety of seasonings to make your dishes flavorful.": "王子創造了各種調味料，讓您的菜餚更加美味。",
    "Featured Blog": "精選博客",
    "Get inspiration from Prince's recipes and cooking videos": "從王子的食譜和烹飪影片中獲取靈感",
    "Read More": "閱讀更多",
    "Explore home cooking and recipes with Prince": "與王子一起探索家庭烹飪和食譜",
    "Food Review": "美食評論",
    "Like other food lovers, Prince loves trying new food...": "像其他美食愛好者一樣，王子喜歡嘗試新食物...",
    "Explore More": "探索更多",
    "New Recipes": "最新食譜",
    "As a self-taught home cook, Prince has some tips...": "作為一位自學成才的家庭廚師，王子有一些心得...",
    "Cook Now": "立即烹飪",
    "Credit / Debit Card": "信用卡 / 扣帳卡",
    "Please upload payment proof (receipt)": "請上傳付款證明 (收據)",
    "Cardholder Name": "持卡人姓名",
    "e.g. CHEN TAI MAN": "例如: CHEN TAI MAN",
    "Card Number": "卡號",
    "Expiry Date": "到期日",
    "CVC": "驗證碼 (CVC)",
    "Credit card payment is currently unavailable.": "信用卡付款目前無法使用。",
    "Error Details:": "錯誤詳情:",
    "Reload page to retry": "重新載入頁面重試",
    "(System configuration error or missing keys). Please choose another payment method or contact support.": "(系統設定錯誤或金鑰缺失)。請選擇其他付款方式或聯絡支援。",
    "Please add more items to use credit card payment, or choose another payment method.": "請增加更多商品以使用信用卡付款，或選擇其他付款方式。",
    "Coupon:": "優惠券:",
    "Coupon code": "優惠券代碼",
    "Shop": "商店",
    "Default Sorting": "預設排序",
    "Price: Low to High": "價格：低到高",
    "Price: High to Low": "價格：高到低",
    "Show per page:": "每頁顯示：",
    "All Products": "所有產品",
    "Add to Wishlist": "加入我的最愛",
    "No Image": "暫無圖片",
    "No products available.": "暫無產品。",
    "Previous": "上一頁",
    "Next": "下一頁",
    "Extraordinary in the Ordinary": "平凡中的不平凡",
    "Join Prince's culinary journey and enjoy the beautiful things in life!": "加入王子的烹飪之旅，享受生活中的美好事物！",
    "Learn More": "了解更多",
    "Discover More": "探索更多",
    "See the wider world through Prince's eyes...": "透過王子的眼睛看更廣闊的世界...",
    "Customer": "客戶",
    "Customers": "客戶",
    "User Profile": "使用者資料",
    "User Profiles": "使用者資料",
    "Category": "分類",
    "Product": "產品",
    "Products": "產品",
    "Product Image": "產品圖片",
    "Product Images": "產品圖片",
    "Page": "頁面",
    "Pages": "頁面",
    "Payment Method": "付款方式",
    "Payment Methods": "付款方式",
    "Coupon": "優惠券",
    "Coupons": "優惠券",
    "Order": "訂單",
    "Orders": "訂單",
    "Order Item": "訂單項目",
    "Order Items": "訂單項目",
    "Order Note": "訂單備註",
    "Order Notes": "訂單備註",
    "Site Settings": "網站設定",
    "Hero Slide": "首頁輪播圖",
    "Hero Slides": "首頁輪播圖",
    "Sales Dashboard": "銷售儀表板",
    "SKU": "貨號",
    "Discount Price": "折扣價格",
    "Stock": "庫存",
    "Description": "描述",
    "Specifications": "規格",
    "Image": "圖片",
    "Image URL": "圖片網址",
    "Active": "啟用",
    "Created At": "建立時間",
    "Updated At": "更新時間",
    "Sort Order": "排序",
    "Caption": "標題",
    "Title": "標題",
    "Subtitle": "副標題",
    "Content": "內容",
    "Code": "代碼",
    "Instructions": "說明",
    "Requires Proof": "需要證明",
    "Discount Type": "折扣類型",
    "Discount Value": "折扣值",
    "Valid From": "生效日期",
    "Valid To": "失效日期",
    "Order Number": "訂單編號",
    "User Account": "使用者帳號",
    "Customer Name": "客戶名稱",
    "Payment Proof": "付款證明",
    "Discount Amount": "折扣金額",
    "Status": "狀態",
    "Total Amount": "總金額",
    "Unit Price": "單價",
    "Sent to Customer": "發送給客戶",
    "Site Name": "網站名稱",
    "Logo": "標誌",
    "Hero Banner": "首頁橫幅",
    "Hero Title": "首頁標題",
    "Hero Subtitle": "首頁副標題",
    "Hero Button Text": "首頁按鈕文字",
    "Hero Link": "首頁連結",
    "Feature Title": "特色區塊標題",
    "Feature Subtitle": "特色區塊副標題",
    "Feature Image": "特色區塊圖片",
    "Founder Image": "創辦人照片",
    "Founder Name": "創辦人姓名",
    "Founder Intro Title": "創辦人介紹標題",
    "Founder Intro Text": "創辦人介紹文字",
    "Contact Phone": "聯絡電話",
    "Contact Email": "聯絡電郵",
    "Contact Address": "聯絡地址",
    "Footer About": "頁尾關於我們",
    "Footer Copyright": "頁尾版權聲明",
    "SMTP Host": "SMTP 主機",
    "SMTP Port": "SMTP 連接埠",
    "SMTP User": "SMTP 使用者",
    "SMTP Password": "SMTP 密碼",
    "Use TLS": "使用 TLS",
    "From Email": "寄件者電郵",
    "Menu Home Text": "選單主頁文字",
    "Menu Store Text": "選單商店文字",
    "Menu About Text": "選單關於我們文字",
    "Menu Blog Text": "選單博客文字",
    "Menu Contact Text": "選單聯絡我們文字",
    "Menu Tutorial Text": "選單教學文字",
    "Menu Tutorial Link": "選單教學連結",
    "Top Bar Bg Color": "頂部欄背景色",
    "Navbar Bg Color": "導覽列背景色",
    "Navbar Text Color": "導覽列文字色",
    "Navbar Items": "導覽列項目",
    "Product Label Bg Color": "產品標籤背景色",
    "Product Label Text Color": "產品標籤文字色",
    "Percentage": "百分比",
    "Fixed Amount": "固定金額",
    "Created": "已建立",
    "Paid": "已付款",
    "Fulfilling": "備貨中",
    "Partially Shipped": "部分出貨",
    "Shipped": "已出貨",
    "Completed": "已完成",
    "Canceled": "已取消",
    "Returned": "已退貨",
    "Refunded": "已退款",
    "Category Name": "分類名稱",
    "Slug": "代稱 (Slug)",
    "Product Name": "產品名稱",
    "User": "使用者",
    "Message": "訊息",
    "Product Data": "產品資料",
    "Price & Stock": "價格與庫存",
    "Categories & Tags": "分類與標籤",
    "Images": "圖片",
    "Upload an image or enter an image URL (choose one). If both are provided, the uploaded image will be displayed first.": "上傳圖片或輸入圖片網址 (擇一)。如果兩者都提供，將優先顯示上傳的圖片。",
    "Preview": "預覽",
    "Shipping Address": "運送地址",
    "Duplicate selected products": "複製選定的產品",
    "Download Import Template": "下載匯入範本",
    "Batch Upload Product Images (ZIP)": "批次上傳產品圖片 (ZIP)",
    "Basic Settings": "基本設定",
    "Home Banner Settings": "首頁橫幅設定",
    "Feature Section (Middle)": "特色區塊 (中間)",
    "Founder Section (About Us)": "創辦人區塊 (關於我們)",
    "Contact Info (Footer)": "聯絡資訊 (頁尾)",
    "Social Media": "社群媒體",
    "Appearance Settings (Menu & Labels)": "外觀設定 (選單與標籤)",
    "Main Menu Text Settings": "主選單文字設定",
    "Tracking Codes": "追蹤代碼",
    "Email Settings (SMTP)": "電子郵件設定 (SMTP)",
    "Configure SMTP server settings for sending system emails (e.g., password reset).": "設定發送系統郵件 (如密碼重設) 的 SMTP 伺服器。",
    "Stock Status": "庫存狀態",
    "Year": "今年",
    "Last Month": "上個月",
    "This Month": "本月",
    "Last 7 Days": "過去 7 天",
    "Custom:": "自訂範圍:",
    "Query": "查詢",
    "Export CSV": "匯出 CSV",
    "Total Revenue": "總營收",
    "Total Orders": "總訂單數",
    "Average Order Value (AOV)": "平均客單價 (AOV)",
    "Sales Trend Chart": "銷售趨勢圖",
    "Top 10 Selling Products": "熱銷商品 TOP 10",
    "Product Name": "商品名稱",
    "Quantity Sold": "銷量",
    "Revenue": "銷售額",
    "Top 10 Selling Categories": "熱銷分類 TOP 10",
    "Category Name": "分類名稱",
    "Daily Sales Report": "每日銷售明細表",
    "Date": "日期",
    "Average Price": "平均單價",
    "No data available": "尚無資料",
    "Data Error: Product Name is required, please check Excel content.": "資料錯誤：產品名稱為必填，請檢查 Excel 內容。",
    "Order History": "訂單記錄",
    "Profile": "個人資料",
    "Change Password": "更改密碼",
    "My Orders": "我的訂單",
    "You have no orders yet.": "您尚未有任何訂單。",
    "Shop Now": "立即購物",
    "Action": "操作",
    "Username cannot be changed.": "使用者名稱無法更改。",
    "Save Changes": "儲存變更",
    "Data Error: Price is required, please check Excel content.": "資料錯誤：價格為必填，請檢查 Excel 內容。",
    "Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our privacy policy.": "您的個人資料將用於處理您的訂單，支援您在本網站的使用體驗，以及我們的隱私權政策中描述的其他用途。",
    "Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our": "您的個人資料將用於處理您的訂單，支援您在本網站的使用體驗，以及我們的隱私權政策中描述的其他用途，詳見我們的",
    "privacy policy": "隱私權政策",
    "Privacy Policy": "隱私權政策",
    "Terms & Conditions": "條款與細則",
    "I have read and agree to the website": "我已閱讀並同意網站的",
    "terms and conditions": "條款與細則",
    "Add to Cart": "加入購物車",
    "Category:": "分類:",
    "Add to Wishlist": "加入我的最愛",
    "Your wishlist is empty.": "您的願望清單是空的。",
    "Order Details": "訂單詳情",
    "Back to My Account": "返回我的帳戶",
    "Order Notes & History": "訂單備註與記錄",
    "Order Info": "訂單資訊",
    "Order Date": "訂單日期",
    "Not Specified": "未指定",
    "Shipping Info": "運送資訊",
    "Payment Proof Required": "需要付款證明",
    "Please upload payment proof to complete order.": "請上傳付款證明以完成訂單。",
    "Save payment information to my account for future purchases.": "儲存付款資訊到我的帳戶以便日後購物。",
    "No payment methods available, please contact administrator.": "沒有可用的付款方式，請聯絡管理員。",
    "Credit card payment failed, please try again later": "信用卡付款失敗，請稍後再試",
    "Payment not completed, please try again": "付款未完成，請再試一次",
    "Invoice": "發票",
    "INVOICE": "發票",
    "Tel": "電話",
    "Order #": "訂單編號",
    "Bill To": "帳單地址",
    "Item": "項目",
    "Unit Cost": "單價",
    "Qty": "數量",
    "Print Invoice": "列印發票",
    "Back": "返回",
    "Account Locked": "帳戶已鎖定",
    "Your account has been temporarily locked due to multiple failed login attempts.": "由於多次登入失敗，您的帳戶已被暫時鎖定。",
    "Please try again later or contact the administrator.": "請稍後再試或聯絡管理員。",
    "Back to Home": "返回首頁",
    "Order Completed": "訂單已完成",
    "Thank you for your order": "感謝您的訂購",
    "Order Number:": "訂單編號:",
    "Status:": "狀態:",
    "Back to Store": "返回商店",
    "View My Orders": "查看我的訂單",
    "View Order in Admin": "在後台查看訂單",
    "7-Day Return Guarantee": "7天退貨保證",
    "HOME / RESET PASSWORD": "主頁 / 重設密碼",
    "Forgot Password?": "忘記密碼？",
    "Reset Password": "重設密碼",
    "Please enter your username or email address. You will receive a link to create a new password via email.": "請輸入您的使用者名稱或電子郵件地址。您將收到一封包含重設密碼連結的電子郵件。",
    "Error: SKU '%(sku)s' already exists in another product, please ensure SKU is unique.": "錯誤：貨號 '%(sku)s' 已存在於其他產品中，請確保貨號唯一。",
    "Created %(created)d images, updated %(updated)d products": "已建立 %(created)d 張圖片，更新 %(updated)d 個產品",
    "General": "一般資訊",
    "Billing": "帳單資訊",
    "Shipping": "運送資訊",
    "Customer History": "客戶歷史紀錄",
    "Total Orders": "總訂單數",
    "Total Revenue": "總營收",
    "Average Order Value (AOV)": "平均客單價 (AOV)",
    "Order Actions": "訂單操作",
    "Order Notes": "訂單備註",
    "by": "由",
    "System": "系統",
    "(Sent to Customer)": "(已發送給客戶)",
    "Delete Note": "刪除備註",
    "Are you sure?": "您確定嗎？",
    "No notes yet": "尚無備註",
    "Add Note": "新增備註",
    "Enter note...": "輸入備註...",
    "Send to Customer": "發送給客戶",
    "Add": "新增",
    "Please correct the error below.": "請修正以下錯誤。",
    "Please correct the errors below.": "請修正以下錯誤。",
    "Get Price": "取得價格",
    "Unable to get price: ": "無法取得價格：",
    "Connection failed, unable to get price.": "連線失敗，無法取得價格。",
    "Please check network or server logs.": "請檢查網路或伺服器日誌。",
    "Unable to detect Product ID (Please select a product first).": "無法偵測產品 ID (請先選擇產品)。",
    "Backup Manager": "備份管理",
    "+ Create New Backup": "+ 建立新備份",
    "File Name": "檔案名稱",
    "Date": "日期",
    "Size": "大小",
    "Type": "類型",
    "Actions": "操作",
    "Restore": "還原",
    "Delete": "刪除",
    "Are you sure you want to restore this backup? Current data will be replaced.": "您確定要還原此備份嗎？目前的資料將被取代。",
    "Are you sure you want to delete this backup?": "您確定要刪除此備份嗎？",
    "No backups found.": "找不到備份。",
    "Reset Password": "重設密碼",
    "HOME / RESET PASSWORD": "主頁 / 重設密碼",
    "Forgot Password?": "忘記密碼？",
    "Please enter your username or email address. You will receive a link to create a new password via email.": "請輸入您的使用者名稱或電子郵件地址。您將收到一封包含重設密碼連結的電子郵件。",
}

def create_po():
    po = polib.POFile()
    po.metadata = {
        'Project-Id-Version': 'PACKAGE VERSION',
        'Report-Msgid-Bugs-To': '',
        'POT-Creation-Date': '2026-02-06 10:00+0800',
        'PO-Revision-Date': '2026-02-06 10:00+0800',
        'Last-Translator': '',
        'Language-Team': '',
        'Language': 'zh_Hant',
        'MIME-Version': '1.0',
        'Content-Type': 'text/plain; charset=UTF-8',
        'Content-Transfer-Encoding': '8bit',
        'Plural-Forms': 'nplurals=1; plural=0;',
    }

    for msgid, msgstr in translations.items():
        entry = polib.POEntry(
            msgid=msgid,
            msgstr=msgstr
        )
        po.append(entry)

    po.save(po_file_path)
    print(f"Successfully created {po_file_path}")
    
    # Also compile to MO
    mo_file_path = po_file_path.replace('.po', '.mo')
    po.save_as_mofile(mo_file_path)
    print(f"Successfully compiled to {mo_file_path}")

if __name__ == "__main__":
    create_po()
