# Generated by Django 5.2.9 on 2026-01-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileIntegrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(max_length=64)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_modified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BackupManager',
            fields=[
            ],
            options={
                'verbose_name': 'Backup Manager',
                'verbose_name_plural': 'Backup Manager',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.pagevisit',),
        ),
    ]
