# Generated by Django 5.2.9 on 2026-01-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_fileintegrity_backupmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileintegrity',
            options={'verbose_name': '檔案完整性', 'verbose_name_plural': '檔案完整性'},
        ),
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-timestamp'], 'verbose_name': '訪客紀錄', 'verbose_name_plural': '訪客紀錄'},
        ),
        migrations.AlterField(
            model_name='fileintegrity',
            name='file_hash',
            field=models.CharField(max_length=64, verbose_name='雜湊值'),
        ),
        migrations.AlterField(
            model_name='fileintegrity',
            name='file_path',
            field=models.CharField(max_length=255, unique=True, verbose_name='檔案路徑'),
        ),
        migrations.AlterField(
            model_name='fileintegrity',
            name='is_modified',
            field=models.BooleanField(default=False, verbose_name='是否被修改'),
        ),
        migrations.AlterField(
            model_name='fileintegrity',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, verbose_name='最後檢查'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='瀏覽器'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='國家'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='裝置類型'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作業系統'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(max_length=255, verbose_name='路徑'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='referer',
            field=models.URLField(blank=True, null=True, verbose_name='來源'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
