# Generated by Django 5.2.9 on 2026-01-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_fileintegrity_options_alter_pagevisit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStatistics',
            fields=[
            ],
            options={
                'verbose_name': '網店統計系統',
                'verbose_name_plural': '網店統計系統',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.pagevisit',),
        ),
    ]
