# Generated by Django 5.2.9 on 2026-02-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_pagevisit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='國家代碼'),
        ),
    ]
